export const translation = {
	hello: 'здравствуй слово',
	conversationTitle: 'Список разговоров',
	deleteCvs: 'Удалить беседу',
	clearMsgs: 'Очистить сообщения',
	image: 'Картина',
	audio: 'Аудио сообщение',
	video: 'Видео сообщение',
	file: 'Файл',
	custom: 'Пользовательское сообщение',
	combine: 'Комбинированное сообщение',
	noConversation: 'Нет разговора',
	recording: 'Запись',
	you: 'Ты',
	repliedTo: 'ответил на',
	messageNotFound: 'Цитируемый контент не существует',
	replyingTo: 'Ответ на',
	delete: 'Удалить',
	reply: 'Отвечать',
	unsend: 'Отзывать',
	attachment: 'Вложение',
	unsentAMessage: ' вспомнил сообщение',
	translate: 'Переводить',
	translated: 'Переведено',
	translationFailed: 'перевод не выполнен',
	translating: 'Идет перевод',
	modify: 'Редактировать',
	modifyTitle: 'Редактировать сообщение',
	confirmBtn: 'Подтверждать',
	cancelBtn: 'Отмена',
	retry: 'Повторить попытку',
	hide: 'Скрывать',
	show: 'Показывать',
	atAll: 'Все',
	atTag: '[Кто-то@Ты] ',
	atAllTag: '[@Все] ',
	select: 'Выбирать',
	chatHistory: 'История чата',
	batchDeletion: 'Пакетное удаление',
	messages: 'Сообщения?',
	cancel: 'Отмена',
	startedBy: 'Начато',
	createThread: 'Создать тему',
	threadNameRequired: 'Название темы (обязательно)',
	enterThreadName: 'Введите название темы',
	aThread: 'Нить',
	edited: 'Сообщение изменено',
	send: 'Отправлять',
	forward: 'Вперед',
	more: 'Более',
	emoji: 'Эмодзи',
	record: 'Записывать',
	resend: 'Отправить',
	unsupportedMessageType: 'Неподдерживаемый тип сообщения',
};